media:
  input: /
  output: /

content:
  - name: pet-shop
    label: My Pet Shop Website
    type: document
    path: index.html
    fields:
      - name: body
        label: Edit Whole Website
        type: rich-text